### ISSUE TITLE
upgrade to marawa 0.8.0-beta.3

### ISSUE THREAD

**Issue by nvdk** [lblod/harvesting-import-service#2]
This release of marawa incorporated the Triple class that's present in this repository. As such the triple class can then be removed here and you can just call `.toNT()` on each triple directly.

e.g. 
`.map(t => new Triple(t));` can be removed from
https://github.com/lblod/harvesting-import-service/blob/97606a732320adf9d9a46940afcf9087b5bc628d/lib/rdfa-extractor.js#L14

**Comment by cecemel** [comment]
Currently closing, as we move towards other library
